valuesYaml:
  replicaCount: 1
  logLevel: info
  backend:
  backends: []
  ui:
    color: "#34577c"
    message: ''
    logo: ''
  faults:
    delay: false
    error: false
    unhealthy: false
    unready: false
    testFail: false
    testTimeout: false
  h2c:
    enabled: false
  image:
    repository: ghcr.io/stefanprodan/podinfo
    tag: 5.1.2
    pullPolicy: IfNotPresent
  service:
    enabled: true
    type: ClusterIP
    metricsPort: 9797
    httpPort: 9898
    externalPort: 9898
    grpcPort: 9999
    grpcService: podinfo
    nodePort: 31198
    hostPort:
  tls:
    enabled: false
    secretName:
    certPath: "/data/cert"
    port: 9899
    hostPort:
  certificate:
    create: false
    issuerRef:
      kind: ClusterIssuer
      name: self-signed
    dnsNames:
    - podinfo
  hpa:
    enabled: false
    maxReplicas: 10
    cpu:
    memory:
    requests:
  cache: ''
  redis:
    enabled: false
    repository: redis
    tag: 6.0.8
  serviceAccount:
    enabled: false
    name:
  linkerd:
    profile:
      enabled: false
  serviceMonitor:
    enabled: false
    interval: 15s
  ingress:
    enabled: false
    annotations: {}
    path: "/*"
    hosts: []
    tls: []
  resources:
    limits:
    requests:
      cpu: 1m
      memory: 16Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
metadata: {}
name: podinfo
